name: test_apps
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.1
  google_nav_bar: ^5.0.4
  font_awesome_flutter: ^10.2.2
  material_design_icons_flutter: ^7.0.0
  curved_navigation_bar: ^1.0.3
  persistent_bottom_nav_bar: ^5.0.2
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:             
    - images/mie.jpg
    - images/pante.jpg
    - images/kereta.jpg
    - images/lhokseumawe.jpg
    - images/kuliner_images/
    - images/popular_images/
